package emulator

const (
	SDL_SCANCODE_SEMICOLON      = 51
	SDL_SCANCODE_APOSTROPHE     = 52
	SDL_SCANCODE_GRAVE          = 53
	SDL_SCANCODE_COMMA          = 54
	SDL_SCANCODE_PERIOD         = 55
	SDL_SCANCODE_SLASH          = 56
	SDL_SCANCODE_NONUSHASH      = 50
	SDL_SCANCODE_NONUSBACKSLASH = 100
)
