package emulator

const (
	SDL_SCANCODE_NUMLOCKCLEAR = 83 /**< num lock on PC clear on Mac keyboards
	 */
	SDL_SCANCODE_KP_DIVIDE   = 84
	SDL_SCANCODE_KP_MULTIPLY = 85
	SDL_SCANCODE_KP_MINUS    = 86
	SDL_SCANCODE_KP_PLUS     = 87
	SDL_SCANCODE_KP_ENTER    = 88
	SDL_SCANCODE_KP_1        = 89
	SDL_SCANCODE_KP_2        = 90
	SDL_SCANCODE_KP_3        = 91
	SDL_SCANCODE_KP_4        = 92
	SDL_SCANCODE_KP_5        = 93
	SDL_SCANCODE_KP_6        = 94
	SDL_SCANCODE_KP_7        = 95
	SDL_SCANCODE_KP_8        = 96
	SDL_SCANCODE_KP_9        = 97
	SDL_SCANCODE_KP_0        = 98
	SDL_SCANCODE_KP_PERIOD   = 99
	SDL_SCANCODE_KP_EQUALS   = 103
)
